# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Main theme"
license = "MIT"
licenselink = "-"
description = "A Base theme"
homepage = ""
tags = ["website"]
features = []
min_version = 0.25

[author]
  name = "Kyle Welch"
  homepage = "https://github.com/k4l397"
